version: '3'

services:
  web:
    image:
      nginx:latest
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "8000:80"
    tty: true
    volumes:
      - ./code:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  php:
    image:
      php:8-fpm
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./code:/code
    ports:
      - "9000:9000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
